### ISSUE TITLE
Add Attribution statement to the leaflet map

### ISSUE THREAD

**Issue by mattdebont** [jncc/deli#27]
We really should add an attribution statement to the leaflet map, for the baselayer and for the data itself

**Comment by completer** [comment]
Attribution is turn off in the code. Can't find a legitimate reason, so enabling. I guess the reason was to remove the Leaflet link - which is [allowed](https://groups.google.com/forum/#!msg/leaflet-js/fA6M7fbchOs/JTNVhqdc7JcJ). The copyright / licence notices in general could be clearer, somehow. Ideally we need a list of each layer on the map, perhaps under the map.
